version: "3"
services:
  insightpython:
    image: insightpython
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - insightproject

networks:
  insightproject:
